<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
     <string>content</string>
  </array>
  <key>name</key>
  <string>.content</string>
  <key>patterns</key>
  <array>
    <!-- Property id,securityparent,inputtemplate,name constant.other.content-->
    <dict>
      <key>begin</key>
      <string>(id|numericalid|securityparent|inputtemplate|name|file)(:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(.*)</string>
      <key>name</key>
      <string>string.content</string>
    </dict>
    <!-- Property major and valid majors -->
    <dict>
      <key>begin</key>
      <string>(major)(:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(majorconfig|article|department|content|layoutelement|workflowtype|workflow|referencemetadata|inputtemplate|outputtemplate|appconfig|userdata|community)</string>
      <key>name</key>
      <string>constant.language.content</string>
    </dict>
    <!-- Property action and valid actions -->
    <dict>
      <key>begin</key>
      <string>(action)(:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(approve|remove|draft)</string>
      <key>name</key>
      <string>constant.language.content</string>
    </dict>
    <!-- Property component -->
    <dict>
      <key>begin</key>
      <string>(component)(:)([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)(:)([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)(:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>constant.other.content</string>
        </dict>
        <key>4</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>5</key>
        <dict>
        <key>name</key>
          <string>support.function.content</string>
        </dict>
        <key>6</key>
        <dict>
        <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(.*)</string>
      <key>name</key>
      <string>string .content</string>
    </dict>
    <!-- Property ref -->
    <dict>
      <key>begin</key>
      <string>(ref)(:)([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)(:)([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)(:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>constant.other.content</string>
        </dict>
        <key>4</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>5</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>6</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
      </dict>
      <key>end</key>
      <string>(.*)</string>
      <key>name</key>
      <string>string.content</string>
    </dict>
    <!-- Property list -->
    <dict>
      <key>begin</key>
      <string>(list)(:)([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)(:)([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)(:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>constant.other.content</string>
        </dict>
        <key>4</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
         <key>5</key>
        <dict>
          <key>name</key>
          <string>support.function.content</string>
        </dict>
        <key>6</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
      </dict>
      <key>end</key>
      <string>([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)</string>
      <key>name</key>
      <string>string.content</string>
    </dict>
    <!-- Property list -->
    <dict>
      <key>begin</key>
      <string>(list)(:)([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)(:)</string>
      <key>beginCaptures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
        <key>3</key>
        <dict>
          <key>name</key>
          <string>constant.other.content</string>
        </dict>
        <key>4</key>
        <dict>
          <key>name</key>
          <string>keyword.properties.content</string>
        </dict>
      </dict>
      <key>end</key>
      <string>([a-zA-Z0-9_\-\.\\\/\[\]\s+]+)</string>
      <key>name</key>
      <string>string.content</string>
    </dict>

  </array>
  <key>scopeName</key>
  <string>source.content</string>
  <key>uuid</key>
  <string>2B64A570-16C9-11E2-892E-0800200C9A66</string>
</dict>
</plist>
